export default {
  /**
   * 通用接口
   */
  //获取github配置仓库中的json
  getConfigJsonInGithub:{
    method:'get',
    url:'/api/github/get-config-json'
  },
  //获取本机Ip
  getLocalIp:{
    method:'get',
    url:'/api/github/get-local-ip'
  },
  /**
   * 代理服务
   */
  //获取代理服务列表
  getProxyServerList:{
    method:'post',
    url:'/api/proxy-server/server-list'
  },
  //添加代理服务
  addProxyServer:{
    method:'post',
    url:'/api/proxy-server/add-server'
  },
  //更新代理服务
  updateProxyServer:{
    method:'post',
    url:'/api/proxy-server/update-server'
  },
  //删除代理服务
  deleteProxyServer:{
    method:'delete',
    url:'/api/proxy-server/delete-server'
  },
  //更改代理服务状态
  changeProxyServerStatus:{
    method:'get',
    url:'/api/proxy-server/change-server-status'
  },
  //获取代理规则列表
  getProxyRuleList:{
    method:'get',
    url:'/api/proxy-server/rule-list'
  },
  //新增代理规则
  addProxyRule:{
    method:'post',
    url:'/api/proxy-server/add-rule'
  },
  //更新代理规则
  updateProxyRule:{
    method:'post',
    url:'/api/proxy-server/update-rule'
  },
  //删除代理规则
  deleteProxyRule:{
    method:'delete',
    url:'/api/proxy-server/delete-rule'
  },
  /**
   * 主机管理
   */
  //获取主机列表
  getHostList:{
    method:'get',
    url:'/api/host-management/host-list'
  },
  //新增主机
  addHost:{
    method:'post',
    url:'/api/host-management/add-host'
  },
  //编辑主机
  editHost:{
    method:'post',
    url:'/api/host-management/edit-host'
  },
  //删除主机
  deleteHost:{
    method:'delete',
    url:'/api/host-management/delete-host'
  }
}
