name: CI

on:
    push:
        branches:
          - 'master'
    pull_request:
        branches:
          - '*'

jobs:
    setup:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14.x, 16.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: yarn

            - name: Run Prettier
              run: yarn prettier

            - name: Run Eslint
              run: yarn eslint

            - name: Run Stylelint
              run: yarn stylelint

            - name: Run check-types
              run: yarn check-types

            - name: Run build
              run: yarn build
